import { getPayload } from 'payload'
import config from '@payload-config'
import { NextResponse } from 'next/server'

// Datos de TODOS los Especialistas con sus colegios asignados
const especialistasData = [
  // =====================================================
  // INICIAL - 4 Especialistas
  // =====================================================
  {
    nombre: 'ALMIDA LOPEZ ESPIRITU',
    nivel: 'inicial',
    presentacion: 'Especialista comprometida con el desarrollo educativo del nivel inicial.',
    colegios: [
      { ubicacion: 'ATAHUAYON', colegio: '274', nivel_modalidad: 'Inicial' },
      { ubicacion: 'RONDONI', colegio: '550', nivel_modalidad: 'Inicial' },
      { ubicacion: 'URAMBISA', colegio: '33368', nivel_modalidad: 'Inicial' },
      { ubicacion: 'YAPAC', colegio: '332', nivel_modalidad: 'Inicial' },
      { ubicacion: 'RACRAY', colegio: '367', nivel_modalidad: 'Inicial' },
      { ubicacion: 'COLPAS', colegio: '166', nivel_modalidad: 'Inicial' },
      { ubicacion: 'PORVENIR', colegio: '33249', nivel_modalidad: 'Inicial' },
      { ubicacion: 'UTCUSH', colegio: '288', nivel_modalidad: 'Inicial' },
      { ubicacion: 'SAN FRANCISCO DE MOSCA', colegio: '117', nivel_modalidad: 'Inicial' },
      { ubicacion: 'CHUCCHUC', colegio: '299', nivel_modalidad: 'Inicial' },
      { ubicacion: 'COCHATAMA', colegio: '232', nivel_modalidad: 'Inicial' },
      { ubicacion: 'QUIO', colegio: '165', nivel_modalidad: 'Inicial' },
      { ubicacion: 'CAYNA', colegio: '58', nivel_modalidad: 'Inicial' },
      { ubicacion: 'SAN ANTONIO DE QUIRCAN', colegio: '32188', nivel_modalidad: 'Inicial' },
      { ubicacion: 'PUCASINIEGA', colegio: '32744', nivel_modalidad: 'Inicial' },
      { ubicacion: 'MOSCATUNA', colegio: '551', nivel_modalidad: 'Inicial' },
      { ubicacion: 'MARAYPATA', colegio: '32169 DAYSI YENY SOTO MORY', nivel_modalidad: 'Inicial' },
      {
        ubicacion: 'ACOCHACAN',
        colegio: '32733 CESAR MORALES NEGRETE',
        nivel_modalidad: 'Inicial',
      },
      { ubicacion: 'RODEO', colegio: '287', nivel_modalidad: 'Inicial' },
      { ubicacion: 'ANGASMARCA', colegio: '330', nivel_modalidad: 'Inicial' },
      { ubicacion: 'COCHAPATA', colegio: '842', nivel_modalidad: 'Inicial' },
      { ubicacion: 'CARACALLA', colegio: '32154', nivel_modalidad: 'Inicial' },
      { ubicacion: 'RACCHA', colegio: '32182', nivel_modalidad: 'Inicial' },
      {
        ubicacion: 'SAN JUAN DE YANAMACHAY',
        colegio: '32747 TUPAC AMARU II',
        nivel_modalidad: 'Inicial',
      },
      { ubicacion: 'HUACAPUCLLANA', colegio: '32894', nivel_modalidad: 'Inicial' },
      { ubicacion: 'SAN MIGUEL DE HUACAR', colegio: '59', nivel_modalidad: 'Inicial' },
      { ubicacion: 'YANACOCHA', colegio: '32746', nivel_modalidad: 'Inicial' },
      { ubicacion: 'COQUIN', colegio: '214', nivel_modalidad: 'Inicial' },
      { ubicacion: 'SACSAHUANCA', colegio: '308', nivel_modalidad: 'Inicial' },
      { ubicacion: 'LOMAS GORDAS', colegio: '33018', nivel_modalidad: 'Inicial' },
    ],
  },
  {
    nombre: 'LYZ SARA MATOS CRISTOBAL',
    nivel: 'inicial',
    presentacion: 'Especialista comprometida con el desarrollo educativo del nivel inicial.',
    colegios: [
      { ubicacion: 'HUARACALLA', colegio: '164', nivel_modalidad: 'Inicial' },
      { ubicacion: 'SAN JOAQUIN', colegio: '381', nivel_modalidad: 'Inicial' },
      { ubicacion: 'ALCAS', colegio: '32198', nivel_modalidad: 'Inicial' },
      { ubicacion: 'QUEROJAMANAN', colegio: '32192', nivel_modalidad: 'Inicial' },
      { ubicacion: 'SALAPAMPA', colegio: '309', nivel_modalidad: 'Inicial' },
      { ubicacion: 'HUANCAHUASI', colegio: '33083', nivel_modalidad: 'Inicial' },
      { ubicacion: 'RAMOS RAGRA', colegio: '33028', nivel_modalidad: 'Inicial' },
      { ubicacion: 'ACLACANCHA', colegio: '32139', nivel_modalidad: 'Inicial' },
      { ubicacion: 'AMBO', colegio: 'CIENCIAS', nivel_modalidad: 'Inicial' },
      { ubicacion: 'ANDAHUAYLLA', colegio: '276', nivel_modalidad: 'Inicial' },
      { ubicacion: 'HUANDOBAMBA', colegio: '259', nivel_modalidad: 'Inicial' },
      { ubicacion: 'CHAUCHA', colegio: '134', nivel_modalidad: 'Inicial' },
      { ubicacion: 'COYLLAR', colegio: '32687', nivel_modalidad: 'Inicial' },
      { ubicacion: 'ÑAUSILLA', colegio: '32777', nivel_modalidad: 'Inicial' },
      { ubicacion: 'AMBO', colegio: '445 JULIO BENAVIDES SANGUINETTI', nivel_modalidad: 'Inicial' },
      { ubicacion: 'AMBO', colegio: 'ISCO', nivel_modalidad: 'Inicial' },
      { ubicacion: 'LLUNCO', colegio: '32882 ISABEL FLORES DE OLIVA', nivel_modalidad: 'Inicial' },
      { ubicacion: 'TECTE', colegio: '191 DIVINO NIÑO JESUS', nivel_modalidad: 'Inicial' },
      { ubicacion: 'AYANCOCHA', colegio: '133', nivel_modalidad: 'Inicial' },
      { ubicacion: 'AMBO', colegio: '43', nivel_modalidad: 'Inicial' },
      { ubicacion: 'ICHOCAN', colegio: '32644', nivel_modalidad: 'Inicial' },
      { ubicacion: 'MARACANA', colegio: '534', nivel_modalidad: 'Inicial' },
      { ubicacion: 'AMBO', colegio: '514', nivel_modalidad: 'Inicial' },
      { ubicacion: 'AMBO', colegio: '167', nivel_modalidad: 'Inicial' },
      { ubicacion: 'UNGUYMARAN', colegio: '515', nivel_modalidad: 'Inicial' },
      { ubicacion: 'OCUCALLA', colegio: 'OCUCALLA', nivel_modalidad: 'Inicial' },
      { ubicacion: 'AMBO', colegio: 'SAN MARCOS', nivel_modalidad: 'Inicial' },
      { ubicacion: 'HUAYLLA', colegio: '163', nivel_modalidad: 'Inicial' },
      { ubicacion: 'CUMBE', colegio: '32693', nivel_modalidad: 'Inicial' },
      { ubicacion: 'AMBO', colegio: '290 JUAN JOSE CRESPO Y CASTILLO', nivel_modalidad: 'Inicial' },
      { ubicacion: 'PILLAO', colegio: '420 DE PILLAO', nivel_modalidad: 'Inicial' },
      { ubicacion: 'AMBO', colegio: '32133 VIRGEN DEL CARMEN', nivel_modalidad: 'Inicial' },
      { ubicacion: 'MAGAPASH', colegio: '516', nivel_modalidad: 'Inicial' },
    ],
  },
  {
    nombre: 'MAGLORIO ORTIZ ROJAS',
    nivel: 'inicial',
    presentacion: 'Especialista comprometido con el desarrollo educativo del nivel inicial.',
    colegios: [
      { ubicacion: 'SAN PEDRO DE ACOBAMBA', colegio: '200', nivel_modalidad: 'Inicial' },
      { ubicacion: 'AMBO', colegio: 'SAGRADO CORAZON DE JESUS', nivel_modalidad: 'Inicial' },
      { ubicacion: 'TINGO', colegio: '33290', nivel_modalidad: 'Inicial' },
      {
        ubicacion: 'SAN MIGUEL DE HUACAR',
        colegio: 'SANTA MARIA DE GUADALUPE',
        nivel_modalidad: 'Inicial',
      },
    ],
  },
  {
    nombre: 'MARIA ELENA MEZA FERNANDEZ',
    nivel: 'inicial',
    presentacion: 'Especialista comprometida con el desarrollo educativo del nivel inicial.',
    colegios: [
      { ubicacion: 'RONDOS', colegio: '329', nivel_modalidad: 'Inicial' },
      { ubicacion: 'QUICACAN', colegio: '258', nivel_modalidad: 'Inicial' },
      { ubicacion: 'LAS PAMPAS', colegio: '199', nivel_modalidad: 'Inicial' },
      { ubicacion: 'MATIHUACA', colegio: '91', nivel_modalidad: 'Inicial' },
      { ubicacion: 'ÑAUZA', colegio: '277', nivel_modalidad: 'Inicial' },
      { ubicacion: 'YAURIN', colegio: '32996', nivel_modalidad: 'Inicial' },
      { ubicacion: '1 DE MAYO', colegio: '33108', nivel_modalidad: 'Inicial' },
      {
        ubicacion: 'ESTANCIA PATA',
        colegio: '32818 EVERARDO ZEVALLOS AVILA',
        nivel_modalidad: 'Inicial',
      },
      {
        ubicacion: 'AYANCOCHA ALTA',
        colegio: '32732 JOSE GALVEZ BARRENECHEA',
        nivel_modalidad: 'Inicial',
      },
      { ubicacion: 'PUCARA', colegio: '552', nivel_modalidad: 'Inicial' },
      { ubicacion: 'ARMATANGA', colegio: '769', nivel_modalidad: 'Inicial' },
      { ubicacion: 'CARAMPAYOG', colegio: '32645', nivel_modalidad: 'Inicial' },
      { ubicacion: 'AMBO', colegio: 'HESSEN', nivel_modalidad: 'Inicial' },
      {
        ubicacion: 'CONCHAMARCA',
        colegio: '046 MOISES JUAN PUENTE ALVARADO',
        nivel_modalidad: 'Inicial',
      },
      { ubicacion: 'CANCHAPARAN', colegio: '275', nivel_modalidad: 'Inicial' },
      { ubicacion: 'TUCNA', colegio: '32762', nivel_modalidad: 'Inicial' },
      { ubicacion: 'SAN RAFAEL', colegio: '45', nivel_modalidad: 'Inicial' },
      { ubicacion: 'CORRALCANCHA', colegio: '32201', nivel_modalidad: 'Inicial' },
      { ubicacion: 'TOMAYQUICHUA', colegio: '044 SANTA ROSA', nivel_modalidad: 'Inicial' },
      { ubicacion: 'HURACHIMPA', colegio: '513', nivel_modalidad: 'Inicial' },
      { ubicacion: 'CHINCHUBAMBA', colegio: '32771', nivel_modalidad: 'Inicial' },
      { ubicacion: 'COCHACALLA', colegio: '110', nivel_modalidad: 'Inicial' },
      { ubicacion: 'SAN RAFAEL', colegio: 'SAN MARCOS', nivel_modalidad: 'Inicial' },
      { ubicacion: 'CHACOS', colegio: '118', nivel_modalidad: 'Inicial' },
      { ubicacion: 'SAN MIGUEL DE RANCAY', colegio: '331', nivel_modalidad: 'Inicial' },
      {
        ubicacion: 'ACOBAMBA',
        colegio: '32199 JOSUE MANUEL GUTIERREZ CONDOR',
        nivel_modalidad: 'Inicial',
      },
      { ubicacion: 'SANTA ROSA DE MARCAMAYO', colegio: '841', nivel_modalidad: 'Inicial' },
      { ubicacion: 'AMBO', colegio: 'GALILEO GALILEI COLLEGE', nivel_modalidad: 'Inicial' },
    ],
  },

  // =====================================================
  // PRIMARIA - 6 Especialistas
  // =====================================================
  {
    nombre: 'CARMEN PAULINA GOMEZ GODOY',
    nivel: 'primaria',
    presentacion: 'Especialista comprometida con el desarrollo educativo del nivel primario.',
    colegios: [
      { ubicacion: 'TINGO', colegio: '33290', nivel_modalidad: 'Primaria' },
      {
        ubicacion: 'ACOCHACAN',
        colegio: '32733 CESAR MORALES NEGRETE',
        nivel_modalidad: 'Primaria',
      },
      { ubicacion: 'AMBO', colegio: 'HESSEN', nivel_modalidad: 'Primaria' },
      { ubicacion: 'YANACOCHA', colegio: '32746', nivel_modalidad: 'Primaria' },
      { ubicacion: 'HUAYLLA', colegio: '32138 MIGUEL GRAU SEMINARIO', nivel_modalidad: 'Primaria' },
      { ubicacion: 'SAN CRISTOBAL', colegio: '32991', nivel_modalidad: 'Primaria' },
      {
        ubicacion: 'SAN PEDRO DE ACOBAMBA',
        colegio: '32183 CESAR VALLEJO',
        nivel_modalidad: 'Primaria',
      },
      { ubicacion: 'COLPAS', colegio: '32147 SAN JUAN', nivel_modalidad: 'Primaria' },
      { ubicacion: 'SAN PABLO DE ACOCHINCHA', colegio: '32588', nivel_modalidad: 'Primaria' },
      { ubicacion: 'MANTACOCHA', colegio: '32179', nivel_modalidad: 'Primaria' },
      { ubicacion: 'PAMPATUPE', colegio: '32170', nivel_modalidad: 'Primaria' },
      { ubicacion: 'CHACATAMA', colegio: '32189', nivel_modalidad: 'Primaria' },
      { ubicacion: 'CHAUCHA', colegio: '32136', nivel_modalidad: 'Primaria' },
      { ubicacion: 'ATAHUAYON', colegio: '33170', nivel_modalidad: 'Primaria' },
      { ubicacion: 'SALAPAMPA', colegio: '32135', nivel_modalidad: 'Primaria' },
      { ubicacion: 'SAN MIGUEL DE RANCAY', colegio: '32826', nivel_modalidad: 'Primaria' },
      { ubicacion: 'RAUQUIN', colegio: '33145', nivel_modalidad: 'Primaria' },
      { ubicacion: 'ESTANCO', colegio: '33017', nivel_modalidad: 'Primaria' },
      { ubicacion: 'SAN JOAQUIN', colegio: '32196', nivel_modalidad: 'Primaria' },
      { ubicacion: 'COCHA PATA', colegio: '32532', nivel_modalidad: 'Primaria' },
      { ubicacion: 'AMBO', colegio: 'JULIO BENAVIDES SANGUINETTI', nivel_modalidad: 'Primaria' },
      { ubicacion: 'QUEROCHACA', colegio: '33422 DE KEROCHACA', nivel_modalidad: 'Primaria' },
      { ubicacion: 'TUCNA', colegio: '32762', nivel_modalidad: 'Primaria' },
      { ubicacion: 'LAS PAMPAS', colegio: '32203', nivel_modalidad: 'Primaria' },
      { ubicacion: 'TACSHAISLA', colegio: '32893', nivel_modalidad: 'Primaria' },
      { ubicacion: 'ÑAUZA', colegio: '32149 SAN MARTIN DE PORRAS', nivel_modalidad: 'Primaria' },
      { ubicacion: 'PONGA', colegio: '33219', nivel_modalidad: 'Primaria' },
      { ubicacion: 'COCHACHINCHE', colegio: '32152', nivel_modalidad: 'Primaria' },
    ],
  },
  {
    nombre: 'ESTHER DELIA DIAZ ACUÑA',
    nivel: 'primaria',
    presentacion: 'Especialista comprometida con el desarrollo educativo del nivel primario.',
    colegios: [
      { ubicacion: 'RAYHUAN', colegio: '33504', nivel_modalidad: 'Primaria' },
      { ubicacion: 'UCRO MARCA', colegio: '32956', nivel_modalidad: 'Primaria' },
      { ubicacion: 'RETAMAYOC', colegio: 'RETAMAYOC', nivel_modalidad: 'Primaria' },
      {
        ubicacion: 'SAN JUAN DE YANAMACHAY',
        colegio: '32747 TUPAC AMARU II',
        nivel_modalidad: 'Primaria',
      },
      { ubicacion: 'AMBO', colegio: 'GALILEO GALILEI COLLEGE', nivel_modalidad: 'Primaria' },
      { ubicacion: 'IZCORRUMI', colegio: '32883', nivel_modalidad: 'Primaria' },
      { ubicacion: 'PULPUL', colegio: '32186', nivel_modalidad: 'Primaria' },
      { ubicacion: 'AMBO', colegio: 'SAN MARCOS', nivel_modalidad: 'Primaria' },
      { ubicacion: 'HUANCAHUASI', colegio: '33083', nivel_modalidad: 'Primaria' },
      {
        ubicacion: 'HUANDOBAMBA',
        colegio: '32167 JOSE OLAYA BALANDRA',
        nivel_modalidad: 'Primaria',
      },
      { ubicacion: 'CHACOS', colegio: '32193', nivel_modalidad: 'Primaria' },
      { ubicacion: 'URAMBISA', colegio: '33368', nivel_modalidad: 'Primaria' },
      { ubicacion: '1 DE MAYO', colegio: '33108', nivel_modalidad: 'Primaria' },
      { ubicacion: 'HUILLAPARAC', colegio: '32930', nivel_modalidad: 'Primaria' },
      {
        ubicacion: 'AYANCOCHA',
        colegio: '32141 VIRGEN NUESTRA SEÑORA DE LAS MERCEDES',
        nivel_modalidad: 'Primaria',
      },
      { ubicacion: 'QUIO', colegio: 'FERNANDO BELAUNDE TERRY', nivel_modalidad: 'Primaria' },
      { ubicacion: 'COQUIN', colegio: '32146', nivel_modalidad: 'Primaria' },
      { ubicacion: 'SANTA ROSA DE PAQUIAQ', colegio: '32694', nivel_modalidad: 'Primaria' },
      { ubicacion: 'MOSCATUNA', colegio: '32181', nivel_modalidad: 'Primaria' },
      {
        ubicacion: 'YAPAC',
        colegio: '32145 JOSE ANTONIO ENCINAS FRANCO',
        nivel_modalidad: 'Primaria',
      },
      {
        ubicacion: 'SAN FRANCISCO DE MOSCA',
        colegio: 'HERMILIO VALDIZAN',
        nivel_modalidad: 'Primaria',
      },
      { ubicacion: 'HUACCHACANCHA', colegio: '32166', nivel_modalidad: 'Primaria' },
      { ubicacion: 'PARCOY', colegio: '32171 SEÑOR DE LOS MILAGROS', nivel_modalidad: 'Primaria' },
      { ubicacion: 'SAN JUAN DE YANAC', colegio: '32937', nivel_modalidad: 'Primaria' },
      { ubicacion: 'RONDOS', colegio: '32162', nivel_modalidad: 'Primaria' },
    ],
  },
  {
    nombre: 'MARCO ANTONIO PAREDES MUNGUIA',
    nivel: 'primaria',
    presentacion: 'Especialista comprometido con el desarrollo educativo del nivel primario.',
    colegios: [
      { ubicacion: 'HUAMISH', colegio: '32185', nivel_modalidad: 'Primaria' },
      { ubicacion: 'SAN RAFAEL', colegio: '32159 DIVINO MAESTRO', nivel_modalidad: 'Primaria' },
      { ubicacion: 'AMBO', colegio: 'SAGRADO CORAZON DE JESUS', nivel_modalidad: 'Primaria' },
      { ubicacion: 'QUEROJAMANAN', colegio: '32192', nivel_modalidad: 'Primaria' },
      { ubicacion: 'UTCUSH', colegio: '32173', nivel_modalidad: 'Primaria' },
      { ubicacion: 'PICHIPAMPA', colegio: '33454', nivel_modalidad: 'Primaria' },
      { ubicacion: 'SAN MIGUEL DE HUACAR', colegio: '32150', nivel_modalidad: 'Primaria' },
      { ubicacion: 'PUCARA', colegio: '32815', nivel_modalidad: 'Primaria' },
      { ubicacion: 'YANACOCHA', colegio: '32175', nivel_modalidad: 'Primaria' },
      { ubicacion: 'SAONAG', colegio: '32848', nivel_modalidad: 'Primaria' },
      { ubicacion: 'MARABAMBA', colegio: '32761', nivel_modalidad: 'Primaria' },
      {
        ubicacion: 'QUICACAN',
        colegio: '33388 LUISA MARIA CUCULIZA TORRE',
        nivel_modalidad: 'Primaria',
      },
      { ubicacion: 'PUERRAGRA', colegio: '33452', nivel_modalidad: 'Primaria' },
      { ubicacion: 'LUCMAS', colegio: '32204', nivel_modalidad: 'Primaria' },
      { ubicacion: 'MARAURA', colegio: '33027', nivel_modalidad: 'Primaria' },
      { ubicacion: 'COCHAQUILLO', colegio: '32168', nivel_modalidad: 'Primaria' },
      { ubicacion: 'CARACALLA', colegio: '32154', nivel_modalidad: 'Primaria' },
      { ubicacion: 'LLUNCO', colegio: '32882 ISABEL FLORES DE OLIVA', nivel_modalidad: 'Primaria' },
      { ubicacion: 'AMBO', colegio: '32133 VIRGEN DEL CARMEN', nivel_modalidad: 'Primaria' },
      { ubicacion: 'COCHATAMA', colegio: '32157', nivel_modalidad: 'Primaria' },
      { ubicacion: 'MAUCA', colegio: '32178', nivel_modalidad: 'Primaria' },
      { ubicacion: 'CHURACAN', colegio: '32190', nivel_modalidad: 'Primaria' },
      { ubicacion: 'RACCHA', colegio: '32182', nivel_modalidad: 'Primaria' },
      { ubicacion: 'AMBO', colegio: '32140 ANTONIO BRACK EGG', nivel_modalidad: 'Primaria' },
      { ubicacion: 'MATIHUACA', colegio: '32161', nivel_modalidad: 'Primaria' },
      { ubicacion: 'HUISHCA', colegio: '32184', nivel_modalidad: 'Primaria' },
      { ubicacion: 'COYLLAR', colegio: '32687', nivel_modalidad: 'Primaria' },
    ],
  },
  {
    nombre: 'MARCOS ANTONIO ARQUEÑO GARAY',
    nivel: 'primaria',
    presentacion: 'Especialista comprometido con el desarrollo educativo del nivel primario.',
    colegios: [
      { ubicacion: 'AMBO', colegio: 'CIENCIAS', nivel_modalidad: 'Primaria' },
      { ubicacion: 'HUARACALLA', colegio: '32137 ALBERT EINSTEIN', nivel_modalidad: 'Primaria' },
      { ubicacion: 'ACOBAMBILLA', colegio: '32180', nivel_modalidad: 'Primaria' },
      { ubicacion: 'SAN ISIDRO DE AÑAY', colegio: '32156', nivel_modalidad: 'Primaria' },
      { ubicacion: 'SAN RAFAEL', colegio: 'SAN MARCOS', nivel_modalidad: 'Primaria' },
      { ubicacion: 'AMBO', colegio: 'JUAN JOSE CRESPO Y CASTILLO', nivel_modalidad: 'Primaria' },
      { ubicacion: 'TECTE', colegio: '32690', nivel_modalidad: 'Primaria' },
      { ubicacion: 'HUACAPUCLLANA', colegio: '32894', nivel_modalidad: 'Primaria' },
      { ubicacion: 'JIRCANCANCHA', colegio: '32759', nivel_modalidad: 'Primaria' },
      { ubicacion: 'MASQUIN', colegio: '32174', nivel_modalidad: 'Primaria' },
      { ubicacion: 'HURACHIMPA', colegio: '33081', nivel_modalidad: 'Primaria' },
      { ubicacion: 'PORVENIR', colegio: '33249', nivel_modalidad: 'Primaria' },
      {
        ubicacion: 'MARAYPATA',
        colegio: '32169 DAYSI YENY SOTO MORY',
        nivel_modalidad: 'Primaria',
      },
      { ubicacion: 'CORRALCANCHA', colegio: '32201', nivel_modalidad: 'Primaria' },
      { ubicacion: 'ARMATANGA', colegio: '32202', nivel_modalidad: 'Primaria' },
      { ubicacion: 'RINCONADA', colegio: '33169', nivel_modalidad: 'Primaria' },
      { ubicacion: 'NUEVA ESPERANZA', colegio: '33453', nivel_modalidad: 'Primaria' },
      { ubicacion: 'HUANCABAMBA', colegio: '32195', nivel_modalidad: 'Primaria' },
      {
        ubicacion: 'ACOBAMBA',
        colegio: '32199 JOSUE MANUEL GUTIERREZ CONDOR',
        nivel_modalidad: 'Primaria',
      },
      { ubicacion: 'ANDAHUAYLLA', colegio: '32741', nivel_modalidad: 'Primaria' },
      { ubicacion: 'SAN PEDRO DE HUAGAS', colegio: '33220', nivel_modalidad: 'Primaria' },
      { ubicacion: 'CASHAYOG', colegio: '32695', nivel_modalidad: 'Primaria' },
      { ubicacion: 'RACRAY', colegio: '32884', nivel_modalidad: 'Primaria' },
      {
        ubicacion: 'AYANCOCHA ALTA',
        colegio: '32732 JOSE GALVEZ BARRENECHEA',
        nivel_modalidad: 'Primaria',
      },
      { ubicacion: 'ÑAUSILLA', colegio: '32777', nivel_modalidad: 'Primaria' },
    ],
  },
  {
    nombre: 'NOEL GROVER ALVAREZ ALDAVA',
    nivel: 'primaria',
    presentacion: 'Especialista comprometido con el desarrollo educativo del nivel primario.',
    colegios: [
      {
        ubicacion: 'BELLA HUAMALI',
        colegio: '33246 DE BELLA HUAMALI',
        nivel_modalidad: 'Primaria',
      },
      { ubicacion: 'CARAMPAYOG', colegio: '32645', nivel_modalidad: 'Primaria' },
      { ubicacion: 'SAN BORJA', colegio: '32990', nivel_modalidad: 'Primaria' },
      { ubicacion: 'PORVENIR DE OCLLAC', colegio: '33247', nivel_modalidad: 'Primaria' },
      {
        ubicacion: 'CHUCCHUC',
        colegio: '32177 JOSE PEDRO CASTILLO TERRONES',
        nivel_modalidad: 'Primaria',
      },
      { ubicacion: 'VISTOSO', colegio: '32804', nivel_modalidad: 'Primaria' },
      { ubicacion: 'OCUCALLA', colegio: '32191', nivel_modalidad: 'Primaria' },
      { ubicacion: 'ACLACANCHA', colegio: '32139', nivel_modalidad: 'Primaria' },
      {
        ubicacion: 'TOMAYQUICHUA',
        colegio: 'RICARDO FLORES GUTIERREZ',
        nivel_modalidad: 'Primaria',
      },
      { ubicacion: 'LOMAS GORDAS', colegio: '33018', nivel_modalidad: 'Primaria' },
      { ubicacion: 'RODEO', colegio: '32187 LEONCIO PRADO', nivel_modalidad: 'Primaria' },
      { ubicacion: 'VISTA ALEGRE', colegio: '32758', nivel_modalidad: 'Primaria' },
      { ubicacion: 'ICHOCAN', colegio: '32644', nivel_modalidad: 'Primaria' },
      { ubicacion: 'RAMOS RAGRA', colegio: '33028', nivel_modalidad: 'Primaria' },
      { ubicacion: 'YAURIN', colegio: '32996', nivel_modalidad: 'Primaria' },
      { ubicacion: 'NOG NOG', colegio: '32997', nivel_modalidad: 'Primaria' },
      {
        ubicacion: 'ESTANCIA PATA',
        colegio: '32818 EVERARDO ZEVALLOS AVILA',
        nivel_modalidad: 'Primaria',
      },
      { ubicacion: 'ALCAS', colegio: '32198', nivel_modalidad: 'Primaria' },
      { ubicacion: 'CONCHAMARCA', colegio: 'SAN LORENZO', nivel_modalidad: 'Primaria' },
      { ubicacion: 'HUANCALL', colegio: '32527', nivel_modalidad: 'Primaria' },
      {
        ubicacion: 'SAN MIGUEL DE HUACAR',
        colegio: 'SANTA MARIA DE GUADALUPE',
        nivel_modalidad: 'Primaria',
      },
      { ubicacion: 'CAYNA', colegio: 'MANUEL GONZALES PRADA', nivel_modalidad: 'Primaria' },
      { ubicacion: 'CUSHI', colegio: '33327', nivel_modalidad: 'Primaria' },
      { ubicacion: 'RACHACANCHA', colegio: '32957', nivel_modalidad: 'Primaria' },
      { ubicacion: 'PILCOCANCHA', colegio: '33328', nivel_modalidad: 'Primaria' },
    ],
  },
  {
    nombre: 'WALTER MAXIMO RIVERA TADEO',
    nivel: 'primaria',
    presentacion: 'Especialista comprometido con el desarrollo educativo del nivel primario.',
    colegios: [
      { ubicacion: 'UCHUCYACU', colegio: '32647', nivel_modalidad: 'Primaria' },
      { ubicacion: 'SANTA ANA', colegio: '32194', nivel_modalidad: 'Primaria' },
      { ubicacion: 'CUMBE', colegio: '32693', nivel_modalidad: 'Primaria' },
      { ubicacion: 'CHINCHUBAMBA', colegio: '32771', nivel_modalidad: 'Primaria' },
      { ubicacion: 'ANGASMARCA', colegio: '32153 SIMON BOLIVAR', nivel_modalidad: 'Primaria' },
      { ubicacion: 'SAN ANTONIO DE QUIRCAN', colegio: '32188', nivel_modalidad: 'Primaria' },
      {
        ubicacion: 'SACSAHUANCA',
        colegio: '32134 GREGORIO DURAND ESPINOZA',
        nivel_modalidad: 'Primaria',
      },
      { ubicacion: 'BUENA VISTA', colegio: '32155', nivel_modalidad: 'Primaria' },
      { ubicacion: 'YAMOR', colegio: '32176', nivel_modalidad: 'Primaria' },
      { ubicacion: 'SAN SEBASTIAN DE HUISHELGO', colegio: '32656', nivel_modalidad: 'Primaria' },
      { ubicacion: 'PILLAO', colegio: '32197', nivel_modalidad: 'Primaria' },
      { ubicacion: 'CONTADERA', colegio: '33369', nivel_modalidad: 'Primaria' },
      { ubicacion: 'SANTA ROSA DE MARCAMAYO', colegio: '32931', nivel_modalidad: 'Primaria' },
      { ubicacion: 'RONDONI', colegio: '32172', nivel_modalidad: 'Primaria' },
      { ubicacion: 'QUISUARUCRO', colegio: '33082', nivel_modalidad: 'Primaria' },
      { ubicacion: 'QUEPAYACAN', colegio: '33107', nivel_modalidad: 'Primaria' },
      { ubicacion: 'MARAY', colegio: '33146', nivel_modalidad: 'Primaria' },
      { ubicacion: 'HUANCAN', colegio: '32774', nivel_modalidad: 'Primaria' },
      { ubicacion: 'SHUPUSH', colegio: '33178', nivel_modalidad: 'Primaria' },
      { ubicacion: 'COCHACALLA', colegio: 'ESTEBAN PAVLETICH', nivel_modalidad: 'Primaria' },
      { ubicacion: 'PUCASINIEGA', colegio: '32744', nivel_modalidad: 'Primaria' },
      { ubicacion: 'CANCHAPARAN', colegio: '32655', nivel_modalidad: 'Primaria' },
    ],
  },

  // =====================================================
  // SECUNDARIA - 4 Especialistas
  // =====================================================
  {
    nombre: 'JULIO CESAR VICENCIO ROMERO',
    nivel: 'secundaria',
    presentacion: 'Especialista comprometido con el desarrollo educativo del nivel secundario.',
    colegios: [
      { ubicacion: 'CHAUCHA', colegio: 'JORGE CHAVEZ DARTNELL', nivel_modalidad: 'Secundaria' },
      {
        ubicacion: 'SAN RAFAEL',
        colegio: 'VICTOR RAUL HAYA DE LA TORRE',
        nivel_modalidad: 'Secundaria',
      },
      {
        ubicacion: 'TOMAYQUICHUA',
        colegio: 'RICARDO FLORES GUTIERREZ',
        nivel_modalidad: 'Secundaria',
      },
      { ubicacion: 'HUARACALLA', colegio: '32137 ALBERT EINSTEIN', nivel_modalidad: 'Secundaria' },
      {
        ubicacion: 'SAN MIGUEL DE HUACAR',
        colegio: 'GREGORIO CARTAGENA',
        nivel_modalidad: 'Secundaria',
      },
      { ubicacion: 'ANGASMARCA', colegio: '32153 SIMON BOLIVAR', nivel_modalidad: 'Secundaria' },
      { ubicacion: 'CAYNA', colegio: 'MANUEL GONZALES PRADA', nivel_modalidad: 'Secundaria' },
      { ubicacion: 'ÑAUZA', colegio: '32149 SAN MARTIN DE PORRAS', nivel_modalidad: 'Secundaria' },
      { ubicacion: 'AMBO', colegio: 'HESSEN', nivel_modalidad: 'Secundaria' },
      { ubicacion: 'AMBO', colegio: 'GALILEO GALILEI COLLEGE', nivel_modalidad: 'Secundaria' },
    ],
  },
  {
    nombre: 'MARCOS ANTONIO ARQUEÑO GARAY',
    nivel: 'secundaria',
    presentacion: 'Especialista comprometido con el desarrollo educativo del nivel secundario.',
    colegios: [
      {
        ubicacion: 'AYANCOCHA ALTA',
        colegio: '32732 JOSE GALVEZ BARRENECHEA',
        nivel_modalidad: 'Secundaria',
      },
    ],
  },
  {
    nombre: 'RAMON GIOVANNI FIGUEREDO ONEEGLIO',
    nivel: 'secundaria',
    presentacion: 'Especialista comprometido con el desarrollo educativo del nivel secundario.',
    colegios: [
      { ubicacion: 'QUEROJAMANAN', colegio: '32192', nivel_modalidad: 'Secundaria' },
      { ubicacion: 'MATIHUACA', colegio: 'CPED - 32161', nivel_modalidad: 'Secundaria' },
      { ubicacion: 'COCHATAMA', colegio: 'RICARDO PALMA SORIANO', nivel_modalidad: 'Secundaria' },
      {
        ubicacion: 'HUANDOBAMBA',
        colegio: '32167 JOSE OLAYA BALANDRA',
        nivel_modalidad: 'Secundaria',
      },
      { ubicacion: 'CONCHAMARCA', colegio: 'SAN LORENZO', nivel_modalidad: 'Secundaria' },
      { ubicacion: 'AMBO', colegio: 'CIENCIAS', nivel_modalidad: 'Secundaria' },
      {
        ubicacion: 'MARAYPATA',
        colegio: '32169 DAYSI YENY SOTO MORY',
        nivel_modalidad: 'Secundaria',
      },
      { ubicacion: 'AMBO', colegio: 'JULIO BENAVIDES SANGUINETTI', nivel_modalidad: 'Secundaria' },
      { ubicacion: 'SAN JOAQUIN', colegio: '32196', nivel_modalidad: 'Secundaria' },
      {
        ubicacion: 'CHUCCHUC',
        colegio: '32177 JOSE PEDRO CASTILLO TERRONES',
        nivel_modalidad: 'Secundaria',
      },
      { ubicacion: 'COCHACALLA', colegio: 'ESTEBAN PAVLETICH', nivel_modalidad: 'Secundaria' },
      { ubicacion: 'AMBO', colegio: 'SAGRADO CORAZON DE JESUS', nivel_modalidad: 'Secundaria' },
      { ubicacion: 'AMBO', colegio: '32133 VIRGEN DEL CARMEN', nivel_modalidad: 'Secundaria' },
      {
        ubicacion: 'SAN ANTONIO DE QUIRCAN',
        colegio: 'DANIEL ALOMIA ROBLES',
        nivel_modalidad: 'Secundaria',
      },
      { ubicacion: 'UTCUSH', colegio: 'UTCUSH', nivel_modalidad: 'Secundaria' },
      {
        ubicacion: 'ACOBAMBA',
        colegio: '32199 JOSUE MANUEL GUTIERREZ CONDOR',
        nivel_modalidad: 'Secundaria',
      },
      { ubicacion: 'ALCAS', colegio: '32198', nivel_modalidad: 'Secundaria' },
      {
        ubicacion: 'SACSAHUANCA',
        colegio: '32134 GREGORIO DURAND ESPINOZA',
        nivel_modalidad: 'Secundaria',
      },
      { ubicacion: 'RACCHA', colegio: '32182', nivel_modalidad: 'Secundaria' },
      { ubicacion: 'QUIO', colegio: 'FERNANDO BELAUNDE TERRY', nivel_modalidad: 'Secundaria' },
      { ubicacion: 'AMBO', colegio: '32140 ANTONIO BRACK EGG', nivel_modalidad: 'Secundaria' },
      { ubicacion: 'CARAMPAYOG', colegio: '32645', nivel_modalidad: 'Secundaria' },
      {
        ubicacion: 'AYANCOCHA',
        colegio: '32141 VIRGEN NUESTRA SEÑORA DE LAS MERCEDES',
        nivel_modalidad: 'Secundaria',
      },
      {
        ubicacion: 'ESTANCIA PATA',
        colegio: '32818 EVERARDO ZEVALLOS AVILA',
        nivel_modalidad: 'Secundaria',
      },
    ],
  },
  {
    nombre: 'VICTOR RAUL ALBORNOZ FLORES',
    nivel: 'secundaria',
    presentacion: 'Especialista comprometido con el desarrollo educativo del nivel secundario.',
    colegios: [
      { ubicacion: 'PUCASINIEGA', colegio: '32744', nivel_modalidad: 'Secundaria' },
      { ubicacion: 'MOSCATUNA', colegio: '32181', nivel_modalidad: 'Secundaria' },
      { ubicacion: 'ARMATANGA', colegio: '32202', nivel_modalidad: 'Secundaria' },
      {
        ubicacion: 'SAN JUAN DE YANAMACHAY',
        colegio: '32747 TUPAC AMARU II',
        nivel_modalidad: 'Secundaria',
      },
      {
        ubicacion: 'ACOCHACAN',
        colegio: '32733 CESAR MORALES NEGRETE',
        nivel_modalidad: 'Secundaria',
      },
      { ubicacion: 'COLPAS', colegio: 'SAN JUAN', nivel_modalidad: 'Secundaria' },
      { ubicacion: 'CHACOS', colegio: 'CPED - 32193', nivel_modalidad: 'Secundaria' },
      {
        ubicacion: 'YAPAC',
        colegio: '32145 JOSE ANTONIO ENCINAS FRANCO',
        nivel_modalidad: 'Secundaria',
      },
      { ubicacion: 'AMBO', colegio: 'JUAN JOSE CRESPO Y CASTILLO', nivel_modalidad: 'Secundaria' },
      { ubicacion: 'AMBO', colegio: 'SAN MARCOS', nivel_modalidad: 'Secundaria' },
      {
        ubicacion: 'SAN FRANCISCO DE MOSCA',
        colegio: 'HERMILIO VALDIZAN',
        nivel_modalidad: 'Secundaria',
      },
      { ubicacion: 'COQUIN', colegio: '32146 AGROPECUARIO', nivel_modalidad: 'Secundaria' },
      { ubicacion: 'RODEO', colegio: 'LEONCIO PRADO', nivel_modalidad: 'Secundaria' },
      {
        ubicacion: 'SAN PEDRO DE ACOBAMBA',
        colegio: '32183 CESAR VALLEJO',
        nivel_modalidad: 'Secundaria',
      },
    ],
  },

  // =====================================================
  // CEBA - 1 Especialista
  // =====================================================
  {
    nombre: 'RAMON GIOVANNI FIGUEREDO ONEEGLIO',
    nivel: 'ceba',
    presentacion: 'Especialista comprometido con la educación básica alternativa.',
    colegios: [
      { ubicacion: 'AMBO', colegio: 'SAN MARCOS', nivel_modalidad: 'Avanzado' },
      { ubicacion: 'SAN RAFAEL', colegio: 'SAN MARCOS', nivel_modalidad: 'Avanzado' },
      { ubicacion: 'AMBO', colegio: 'SAN MARCOS', nivel_modalidad: 'Inicial e Intermedio' },
      {
        ubicacion: 'AMBO',
        colegio: 'JUAN JOSE CRESPO Y CASTILLO',
        nivel_modalidad: 'Inicial e Intermedio',
      },
    ],
  },

  // =====================================================
  // PRONOI - 1 Especialista
  // =====================================================
  {
    nombre: 'MAGLORIO ORTIZ ROJAS',
    nivel: 'pronoi',
    presentacion: 'Especialista comprometido con la educación inicial no escolarizada.',
    colegios: [
      { ubicacion: 'UNGRO', colegio: 'ENCANTADORES', nivel_modalidad: 'PRONOI' },
      { ubicacion: 'QUEPAYACAN', colegio: 'LOS SOLDADITOS', nivel_modalidad: 'PRONOI' },
      { ubicacion: 'YAMOR', colegio: 'ESTRELLITAS FELICES', nivel_modalidad: 'PRONOI' },
      { ubicacion: 'PONGA', colegio: 'LOS TESORITOS', nivel_modalidad: 'PRONOI' },
      { ubicacion: 'CHACAPAMPA', colegio: '3ROCIO DEL AMANECER', nivel_modalidad: 'PRONOI' },
      { ubicacion: 'RETAMAYOC', colegio: 'RETAMITA DEL MAÑANA', nivel_modalidad: 'PRONOI' },
      { ubicacion: 'CONCHAS', colegio: 'AMANECER DEL SABER', nivel_modalidad: 'PRONOI' },
      { ubicacion: 'PUERRAGRA', colegio: 'SOL NACIENTE', nivel_modalidad: 'PRONOI' },
      { ubicacion: 'HUAMANGAGA', colegio: 'NOBLEZA Y NATURALEZA', nivel_modalidad: 'PRONOI' },
      { ubicacion: 'VISTA ALEGRE', colegio: 'LOS ALEGRES', nivel_modalidad: 'PRONOI' },
      { ubicacion: 'CUSHI', colegio: 'DIVINO NIÑO', nivel_modalidad: 'PRONOI' },
      { ubicacion: 'MARAURA', colegio: 'NIÑOS FELICES', nivel_modalidad: 'PRONOI' },
      { ubicacion: 'MASQUIN', colegio: 'SONRISAS Y COLORES', nivel_modalidad: 'PRONOI' },
      { ubicacion: 'CHANCADORA', colegio: 'GRANDES AMIGUITOS', nivel_modalidad: 'PRONOI' },
      { ubicacion: 'ACOCHINCHA', colegio: 'SARITA COLONIA', nivel_modalidad: 'PRONOI' },
      { ubicacion: 'CUCHICANCHA', colegio: 'EL SAMARITANO', nivel_modalidad: 'PRONOI' },
      { ubicacion: 'PAMPATUPE', colegio: 'SAN MIGUEL', nivel_modalidad: 'PRONOI' },
      { ubicacion: 'SAN BORJA', colegio: 'TRABAJO Y DESARROLLO', nivel_modalidad: 'PRONOI' },
      { ubicacion: 'UCHUCYACU', colegio: 'GOTITAS DE SABIDURIA', nivel_modalidad: 'PRONOI' },
      { ubicacion: 'HUILLAPARAC', colegio: 'LA AMISTAD', nivel_modalidad: 'PRONOI' },
      {
        ubicacion: 'SAN SEBASTIAN DE HUISHELGO',
        colegio: 'SAN LORENZO',
        nivel_modalidad: 'PRONOI',
      },
      { ubicacion: 'CASHAYOG', colegio: 'GIRASOLES', nivel_modalidad: 'PRONOI' },
      { ubicacion: 'HUAMISH', colegio: 'LUZ NACIENTE', nivel_modalidad: 'PRONOI' },
      { ubicacion: 'CHURACAN', colegio: 'SAN MARTIN DE PORRES', nivel_modalidad: 'PRONOI' },
      { ubicacion: 'CRUZ PATA', colegio: 'FE Y ESPERANZA', nivel_modalidad: 'PRONOI' },
      { ubicacion: 'CHASQUI', colegio: 'LOS CONQUISTADORES', nivel_modalidad: 'PRONOI' },
      { ubicacion: 'MARABAMBA', colegio: 'LOS CHIQUITINES', nivel_modalidad: 'PRONOI' },
      { ubicacion: 'SANTA ANA', colegio: 'VIRGEN DEL ROSARIO', nivel_modalidad: 'PRONOI' },
      { ubicacion: 'HUANCABAMBA', colegio: 'VIRGEN DE GUADALUPE', nivel_modalidad: 'PRONOI' },
      { ubicacion: 'ACOBAMBILLA', colegio: 'SAN BENITO', nivel_modalidad: 'PRONOI' },
      { ubicacion: 'COCHACHINCHE', colegio: 'SOLDADITOS DEL SABER', nivel_modalidad: 'PRONOI' },
      { ubicacion: 'HUISHCA', colegio: 'EL PRINCIPITO', nivel_modalidad: 'PRONOI' },
      { ubicacion: 'MANTACOCHA', colegio: 'GOTITAS DE ALEGRIA', nivel_modalidad: 'PRONOI' },
      { ubicacion: 'CASACAN', colegio: 'LUZ Y SABER', nivel_modalidad: 'PRONOI' },
      { ubicacion: 'PILCOCANCHA', colegio: 'LOS NIÑOS DE JESUS', nivel_modalidad: 'PRONOI' },
      { ubicacion: 'CALLANCA', colegio: 'LUZ Y ESPERANZA', nivel_modalidad: 'PRONOI' },
      { ubicacion: 'SAN PEDRO DE HUAGAS', colegio: 'SAN PEDRO', nivel_modalidad: 'PRONOI' },
      { ubicacion: 'INGENIO', colegio: 'LOS CREATIVOS', nivel_modalidad: 'PRONOI' },
      { ubicacion: 'RINCONADA', colegio: 'CORAZON DE JESUS', nivel_modalidad: 'PRONOI' },
      { ubicacion: 'BUENA VISTA', colegio: 'ESPIGUITAS DORADAS', nivel_modalidad: 'PRONOI' },
      { ubicacion: 'CHACATAMA', colegio: 'CARITAS FELICES', nivel_modalidad: 'PRONOI' },
      { ubicacion: 'AÑAY', colegio: 'LOS ANDES', nivel_modalidad: 'PRONOI' },
      { ubicacion: 'SAONAG', colegio: 'ANGELITOS DIVINOS', nivel_modalidad: 'PRONOI' },
    ],
  },
] as const

export async function GET() {
  try {
    const payload = await getPayload({ config })

    // Primero limpiar los especialistas existentes
    const existingDocs = await payload.find({
      collection: 'especialistas',
      limit: 100,
    })

    for (const doc of existingDocs.docs) {
      await payload.delete({
        collection: 'especialistas',
        id: doc.id,
      })
    }

    let count = 0

    // Insertar todos los especialistas
    for (const especialista of especialistasData) {
      await payload.create({
        collection: 'especialistas',
        data: {
          nombre: especialista.nombre,
          nivel: especialista.nivel,
          presentacion: especialista.presentacion,
          colegios: especialista.colegios.map((c) => ({
            ubicacion: c.ubicacion,
            colegio: c.colegio,
            nivel_modalidad: c.nivel_modalidad,
          })),
        },
      })
      count++
    }

    return NextResponse.json({
      success: true,
      message: 'Especialistas sembrados correctamente',
      inserted: count,
      breakdown: {
        inicial: 4,
        primaria: 6,
        secundaria: 4,
        ceba: 1,
        pronoi: 1,
        total: 16,
      },
    })
  } catch (error) {
    console.error('Error seeding especialistas:', error)
    return NextResponse.json(
      {
        success: false,
        error: error instanceof Error ? error.message : 'Error desconocido',
      },
      { status: 500 },
    )
  }
}
