/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    personal: Personal;
    especialistas: Especialista;
    fortalecimiento: Fortalecimiento;
    'noticias-modal': NoticiasModal;
    noticiaintegridads: Noticiaintegridad;
    convocatorias: Convocatoria;
    tutoriales: Tutoriale;
    notificaciones: Notificacione;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    personal: PersonalSelect<false> | PersonalSelect<true>;
    especialistas: EspecialistasSelect<false> | EspecialistasSelect<true>;
    fortalecimiento: FortalecimientoSelect<false> | FortalecimientoSelect<true>;
    'noticias-modal': NoticiasModalSelect<false> | NoticiasModalSelect<true>;
    noticiaintegridads: NoticiaintegridadsSelect<false> | NoticiaintegridadsSelect<true>;
    convocatorias: ConvocatoriasSelect<false> | ConvocatoriasSelect<true>;
    tutoriales: TutorialesSelect<false> | TutorialesSelect<true>;
    notificaciones: NotificacionesSelect<false> | NotificacionesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  /**
   * Define los permisos de acceso del usuario
   */
  role: 'admin' | 'especialista' | 'rrhh' | 'integridad';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * Archivos multimedia almacenados en Cloudinary
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Descripción de la imagen para accesibilidad
   */
  alt: string;
  cloudinaryPublicId?: string | null;
  updatedAt: string;
  createdAt: string;
  /**
   * URL de la imagen en Cloudinary (se genera automáticamente)
   */
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "personal".
 */
export interface Personal {
  id: string;
  nombre: string;
  cargo: string;
  area: 'direccion' | 'rrhh' | 'aga' | 'agi' | 'agp';
  foto?: (string | null) | Media;
  /**
   * Menor número = aparece primero
   */
  orden?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "especialistas".
 */
export interface Especialista {
  id: string;
  nombre: string;
  nivel: 'inicial' | 'primaria' | 'secundaria' | 'ceba' | 'pronoi' | 'convivencia';
  foto?: (string | null) | Media;
  presentacion?: string | null;
  colegios?:
    | {
        ubicacion: string;
        colegio: string;
        nivel_modalidad: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fortalecimiento".
 */
export interface Fortalecimiento {
  id: string;
  titulo: string;
  descripcion?: string | null;
  fecha: string;
  area: 'inicial' | 'primaria' | 'secundaria' | 'pronoi' | 'ceba' | 'convivencia';
  tipo: 'Curso' | 'Charla' | 'Taller' | 'Capacitacion';
  /**
   * URL de Google Drive u otro servicio de almacenamiento
   */
  linkRecursos?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "noticias-modal".
 */
export interface NoticiasModal {
  id: string;
  titulo: string;
  imagen: string | Media;
  /**
   * Desmarcar para ocultar temporalmente sin eliminar
   */
  activo?: boolean | null;
  /**
   * Menor número = aparece primero
   */
  orden?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Gestiona las noticias del área de Integridad y Transparencia
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "noticiaintegridads".
 */
export interface Noticiaintegridad {
  id: string;
  /**
   * Título que aparecerá en la tarjeta y página de detalle
   */
  titulo: string;
  /**
   * Contenido completo de la noticia. En las tarjetas solo se mostrará un extracto.
   */
  descripcion: string;
  fecha: string;
  /**
   * Sube una imagen para la noticia (se almacenará en Cloudinary)
   */
  imagen?: (string | null) | Media;
  /**
   * Área a la que pertenece esta noticia
   */
  area: 'integridad' | 'general';
  /**
   * Desmarcar para ocultar la noticia sin eliminarla
   */
  activo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Gestiona las convocatorias y oportunidades laborales
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "convocatorias".
 */
export interface Convocatoria {
  id: string;
  /**
   * Nombre completo de la convocatoria (ej: "CAS N° 001-2026 - Especialista en Educación")
   */
  nombre: string;
  /**
   * Estado actual del proceso de convocatoria
   */
  estado: 'vigente' | 'en_proceso' | 'concluido' | 'cancelado';
  fechaInicioInscripcion: string;
  fechaFinInscripcion: string;
  fechaResultados?: string | null;
  /**
   * Agrupa los documentos según la etapa del proceso
   */
  archivos?:
    | {
        etapa: 'inscripcion' | 'curricular' | 'entrevista' | 'final' | 'otros';
        documentos?:
          | {
              /**
               * Nombre descriptivo del documento
               */
              nombreArchivo: string;
              /**
               * Enlace de Google Drive al documento (asegúrate de que sea público)
               */
              urlDrive: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Desmarcar para ocultar la convocatoria sin eliminarla
   */
  activo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Gestiona los videos tutoriales para docentes
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tutoriales".
 */
export interface Tutoriale {
  id: string;
  titulo: string;
  /**
   * Breve explicación de lo que trata el tutorial.
   */
  descripcion: string;
  /**
   * Pega el enlace completo del video o el ID (ej: https://www.youtube.com/watch?v=dQw4w9WgXcQ)
   */
  youtubeUrl: string;
  categoria: 'docentes' | 'directivos' | 'otros';
  /**
   * Números menores aparecen primero.
   */
  orden?: number | null;
  /**
   * Desmarcar para ocultar el tutorial.
   */
  activo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Gestiona las notificaciones push enviadas al portal web
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notificaciones".
 */
export interface Notificacione {
  id: string;
  titulo: string;
  mensaje: string;
  /**
   * Cantidad de suscriptores que recibieron la notificación
   */
  enviadoA?: number | null;
  fallidos?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'personal';
        value: string | Personal;
      } | null)
    | ({
        relationTo: 'especialistas';
        value: string | Especialista;
      } | null)
    | ({
        relationTo: 'fortalecimiento';
        value: string | Fortalecimiento;
      } | null)
    | ({
        relationTo: 'noticias-modal';
        value: string | NoticiasModal;
      } | null)
    | ({
        relationTo: 'noticiaintegridads';
        value: string | Noticiaintegridad;
      } | null)
    | ({
        relationTo: 'convocatorias';
        value: string | Convocatoria;
      } | null)
    | ({
        relationTo: 'tutoriales';
        value: string | Tutoriale;
      } | null)
    | ({
        relationTo: 'notificaciones';
        value: string | Notificacione;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  cloudinaryPublicId?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "personal_select".
 */
export interface PersonalSelect<T extends boolean = true> {
  nombre?: T;
  cargo?: T;
  area?: T;
  foto?: T;
  orden?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "especialistas_select".
 */
export interface EspecialistasSelect<T extends boolean = true> {
  nombre?: T;
  nivel?: T;
  foto?: T;
  presentacion?: T;
  colegios?:
    | T
    | {
        ubicacion?: T;
        colegio?: T;
        nivel_modalidad?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fortalecimiento_select".
 */
export interface FortalecimientoSelect<T extends boolean = true> {
  titulo?: T;
  descripcion?: T;
  fecha?: T;
  area?: T;
  tipo?: T;
  linkRecursos?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "noticias-modal_select".
 */
export interface NoticiasModalSelect<T extends boolean = true> {
  titulo?: T;
  imagen?: T;
  activo?: T;
  orden?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "noticiaintegridads_select".
 */
export interface NoticiaintegridadsSelect<T extends boolean = true> {
  titulo?: T;
  descripcion?: T;
  fecha?: T;
  imagen?: T;
  area?: T;
  activo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "convocatorias_select".
 */
export interface ConvocatoriasSelect<T extends boolean = true> {
  nombre?: T;
  estado?: T;
  fechaInicioInscripcion?: T;
  fechaFinInscripcion?: T;
  fechaResultados?: T;
  archivos?:
    | T
    | {
        etapa?: T;
        documentos?:
          | T
          | {
              nombreArchivo?: T;
              urlDrive?: T;
              id?: T;
            };
        id?: T;
      };
  activo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tutoriales_select".
 */
export interface TutorialesSelect<T extends boolean = true> {
  titulo?: T;
  descripcion?: T;
  youtubeUrl?: T;
  categoria?: T;
  orden?: T;
  activo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notificaciones_select".
 */
export interface NotificacionesSelect<T extends boolean = true> {
  titulo?: T;
  mensaje?: T;
  enviadoA?: T;
  fallidos?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}